### ISSUE TITLE
Coinflip - Pika 2.0

### ISSUE THREAD

**Issue by ghost** [littlestudios69/Pika#10] opened 2021-05-02 03:06 UTC
p*coinflip does not respond.
![Screenshot_20210501-230358_Bluecord](https://user-images.githubusercontent.com/83475317/116800741-d9915800-aad1-11eb-9a5f-42d02d2ac748.jpg)

**Comment by ImFelixprogram** [comment] 2021-05-02 08:25
Hi @VerifiedProxy ,
the command itself works and responds, just the correct usage message `p*coinflip <heads/tails> <amount>` is not being displayed.
I'll look for the cause of that error and will implement a fix.

~ Felixprogram, CTO of Little Studios

**Comment by ImFelixprogram** [comment] 2021-05-02 08:45
Fixed with commit [a989304c902292a919133abc0fa1e1ec0c136734](https://github.com/littlestudios69/Pika/commit/a989304c902292a919133abc0fa1e1ec0c136734)

**Closed as completed by ImFelixprogram** 2021-05-02 08:45 UTC
Labels: bug
